### ISSUE TITLE
/thunderbird adopt Sandstone

### ISSUE THREAD

**Issue by irvin** [moztw/central#104]

**Comment by johnroyer** [comment]
ToDo: Some lines of feature introduction is overflow in grid layout.

**Comment by johnroyer** [comment]
Styling page by sandstone layout. And adding Thunderbird introduction from [mozilla.org](http://svn.mozilla.org/projects/mozilla.org/trunk/thunderbird/zh-TW/thunderbird/features/index.html). 

Close 733ff22.

**Comment by irvin** [comment]
Going live now, really closed.
