### ISSUE TITLE
Better description of auto_update.php

### ISSUE THREAD

**Issue by bootleq** [moztw/central#34]
每次原始碼修改後，用來更新線上頁面的 auto_update 頁，
現在有四個選項，但敘述不清，容易不曉得該怎麼選。

應調整顯示文字，讓不小心開到這頁的人也知道它是幹嘛的。

**Comment by petercpg** [comment]
+1, 現在才知道有差 XD

**Comment by petercpg** [comment]
Should be fixed in https://github.com/moztw/central/commit/fb4cf7b298e850e9025ad8009c653e3e18a80ab3
