### ISSUE TITLE
move planet to Github

### ISSUE THREAD

**Issue by petercpg** [moztw/central#42]
Original issue at: http://code.google.com/p/moztw-web/issues/detail?id=83

該改成移進 Github 了。

**Comment by timdream** [comment]
有辦法用 submodule 做嗎？不要 check-in 進這裡管理起來比較好（不會有 local 修改升級的時候需要挑之類的）

**Comment by bobchao** [comment]
比照 forum 另外獨立一個？

**Comment by petercpg** [comment]
submodule 我不確定，但應該是可以？ (為什麼會需要挑?)

比照 forum 另外開 repo 的話就一定可以囉

**Comment by timdream** [comment]
如果我們有 local 修改，那升級（把新檔案蓋上去）的時候就會要把我們自己的修改再 port 到新版本上。

如果用 submodule 就是直接用 upstream 的檔案，不能改 :-/ 但是就不會有升級的麻煩問題。

**Comment by petercpg** [comment]
喔原來是這樣，我還想說 git 裡面能不能再包一個 git upstream repo...

不過我沒記錯的話 planetplanet 不是挺舊的程式，也沒有 repo 可拉？

另一個問題是我們應該沒對這程式本身修改？

**Comment by timdream** [comment]
Planet 應該沒有，phpBB 難說。
原始程式碼在 Gnome Bzr 上面，沒有 Git mirror ... 所以忘了我講的 submodule 吧 T_T

倒是 Planet 的部份可以不要 check-in （改寫下載安裝的 shell script 或是 README），但是 admin/theme 的部份要作，就像這個： https://github.com/phpmyadmin/planet

**Comment by petercpg** [comment]
我也覺得只放設定檔會好一點。

phpBB 的 github repo 在 https://github.com/phpbb/phpbb3，我們要拆成 submodule 的話要考慮安裝的外掛怎麼 merge?

另外之前是不是有人提過看 planet 要不要轉移去 moonmoon? this would be a separate bug though.
