### ISSUE TITLE
Seperate /htdoc to an isolated repo

### ISSUE THREAD

**Issue by irvin** [moztw/central#76]
Seperate /htdoc and related commit to an isolated repo to slim the repo size and ease the clone time,

**Comment by timdream** [comment]
I think `/htdoc` is the repo contains the most of the files :P you are not going to slim the size in any reasonable sense by making a sub-directory repo.

**Comment by irvin** [comment]
The full repo is 530MB, the /htdoc is 170MB and /wiki also consume 73MB, current total file size is 268MB, 
dunno how much space seperating the repo will reduced.

**Comment by timdream** [comment]
你算的是現在的資料夾大小還是 git 紀錄的大小？你已經用 `git filter-branch` 把 sub-directory repo 跑過了嗎？

**Comment by irvin** [comment]
資料夾大小啊，如果去跑完，那我就可以直接 close bug 了……

**Comment by timdream** [comment]
資料夾大小 !== 之後 clone 的大小，差很多 ...

**Comment by irvin** [comment]
我知道，所以才開 bug 等有人去測啊……
上面算大小的意思是除了 htdoc，wiki 也佔很大，所以無法預估分割到底會不會沒什麼效果。
